spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: todo-service
          uri: http://localhost:8100
          predicates:
            - Path=/todo-service/**
          filters:
            - StripPrefix=1
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
            authorization-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/auth
            userinfo-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/userinfo
        registration:
          main:
            provider: keycloak
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/auth/realms/${keycloak.realm}

keycloak:
  url: http://localhost:9999
  realm: todo
  client-id: main
  client-secret: dVfXJXyha4QShlemFlyORTm9cm0q8RMc
