spring:
  cloud:
    gateway:
      routes:
        - id: offer-service
          uri: http://localhost:8100
          predicates:
            - Path=/offer-service/**
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: password
      authentication-database: admin

keycloak:
  url: http://localhost:9999
  realm: finecontract
  client-id: main
  client-secret: dVfXJXyha4QShlemFlyORTm9cm0q8RMc
